<?php

namespace AppHumansBundle\Repository;

/**
 * associationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class associationsRepository extends \Doctrine\ORM\EntityRepository
{
}
