<?php

namespace AppHumansBundle\Repository;

/**
 * beneficiariesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class beneficiariesRepository extends \Doctrine\ORM\EntityRepository
{
}
