<?php

namespace AppHumansBundle\Repository;

/**
 * needRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class needRepository extends \Doctrine\ORM\EntityRepository
{
}
